---
CONTRIBUTING.md:
  unmanaged: true
Gemfile:
  optional:
    ':development':
      - gem: yard
    ':system_tests':
          - gem: beaker-testmode_switcher
            version: '<= 0.2.0'
          - gem: master_manipulator
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
LICENSE:
  license_type: 'puppetpe'
NOTICE:
  unmanaged: true
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
